/**
 * Code quality rules — pure style and correctness, no architecture or framework deps.
 */
export default {
  rules: {
    'clean-arch/curly-multi-or-nest': 'error',
    'clean-arch/inline-single-statement-handlers': 'error',
    'clean-arch/lines-between-class-members': 'error',
    'clean-arch/max-statements-per-line': ['error', { max: 1 }],
    'clean-arch/naming-convention-boolean-prefix': 'error',
    'clean-arch/no-and-or-in-names': 'error',
    'clean-arch/no-complex-inline-arguments': 'error',
    'clean-arch/no-consecutive-duplicate-returns': 'error',
    'clean-arch/no-else-if': 'error',
    'clean-arch/no-enum-value-as-string-literal': 'error',
    'clean-arch/no-i-prefix-in-imports': 'error',
    'clean-arch/no-inline-import-type': 'error',
    'clean-arch/no-inline-object-type': 'error',
    'clean-arch/no-lame-naming': 'error',
    'clean-arch/no-module-level-constants': 'error',
    'clean-arch/no-nested-call-expressions': 'error',
    'clean-arch/no-nested-this-calls': 'error',
    'clean-arch/no-redundant-nullish-ternary': 'error',
    'clean-arch/no-switch': 'error',
    'clean-arch/no-ternary-false-fallback': 'error',
    'clean-arch/object-shorthand': 'error',
    'clean-arch/padding-line-between-block-like': 'error',
    'clean-arch/prefer-array-destructuring': 'error',
    'clean-arch/prefer-enum-over-string-union': 'error',
    'clean-arch/prefer-inline-variable': 'error',
    'clean-arch/prefer-jump-table': 'error',
    'clean-arch/prefer-object-destructuring': 'warn',
    'clean-arch/prefer-ternary-return': 'error',
    'clean-arch/require-named-regex': 'error',
    'clean-arch/time-constant-multiplication': 'error',
    'clean-arch/try-catch-isolation': 'error',
    'clean-arch/no-date-now': 'error',
  },
}
